name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  prepare-release:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.version.outputs.current_version }}
      tag_exists: ${{ steps.tag_check.outputs.tag_exists }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - id: version
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - id: tag_check
        run: |
          if git rev-parse "v${{ steps.version.outputs.current_version }}" >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

  release:
    runs-on: ubuntu-latest
    needs: prepare-release
    if: ${{ needs.prepare-release.outputs.tag_exists == 'false' }}
    steps:
      - uses: actions/checkout@v5

      - name: Add Tag
        run: |
          git tag "v${{ needs.prepare-release.outputs.current_version }}"
          git push origin "v${{ needs.prepare-release.outputs.current_version }}"

      - name: Create Release to GitHub
        run: gh release create "v${{ needs.prepare-release.outputs.current_version }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    runs-on: ubuntu-latest
    needs: prepare-release
    if: ${{ needs.prepare-release.outputs.tag_exists == 'false' }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=v${{ needs.prepare-release.outputs.current_version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  create-addon-update-pr:
    runs-on: ubuntu-latest
    needs: [prepare-release, build-and-publish]
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.repository_owner }}/home-assistant-addons
          token: ${{ secrets.PR_TOKEN }}

      - id: get-version
        name: Get Add-on Version
        run: |
          APP_VERSION="v${{ needs.prepare-release.outputs.current_version }}"
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          ADDON_VERSION="${APP_VERSION}-1"
          echo "addon_version=$ADDON_VERSION" >> $GITHUB_OUTPUT

      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.PR_TOKEN }}" | gh auth login --with-token

      - id: commit-and-push
        name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          yq '.version = "${{ steps.get-version.outputs.addon_version }}"' ./pc2mqtt/config.yaml -i

          CHANGELOG_FILE="./pc2mqtt/CHANGELOG.md"
          NEW_ENTRY="## ${{ steps.get-version.outputs.addon_version }}\n"
          NEW_ENTRY+="- Updated pc2mqtt to version [\`${{ steps.get-version.outputs.app_version }}\`](https://github.com/nana4rider/pc2mqtt/releases/tag/${{ steps.get-version.outputs.app_version }})\n\n"
          echo -e "$NEW_ENTRY$(cat $CHANGELOG_FILE)" > $CHANGELOG_FILE

          git add .
          git commit -m "feat(pc2mqtt): Update add-on version to ${{ steps.get-version.outputs.app_version }}"

          BRANCH_NAME="feature/update-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        run: |
          gh pr create --base main \
                       --head "${{ steps.commit-and-push.outputs.branch_name }}" \
                       --title "Update pc2mqtt to ${{ steps.get-version.outputs.app_version }}" \
                       --body "This pull request updates the pc2mqtt add-on to version [${{ steps.get-version.outputs.app_version }}](https://github.com/nana4rider/pc2mqtt/releases/tag/${{ steps.get-version.outputs.app_version }})"
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
